---
- name: Populate OpenShift with projects
  hosts: masters
  tasks:
    - name: Install openshift python package
      yum: 
          state: latest 
          name: 
            - python2-openshift
    - name: Deploy Cakephp with NO persistent storage
      include_role:
        name: cakephp
    - include_role:
        name: imageuploader
    - include_role:
        name: todoapp
...
