---
- name: Populate OpenShift with projects
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install openshift python package
      yum: 
          state: latest 
          name: 
            - python2-openshift
    - name: Deploy Cakephp with NO persistent storage
      include_role:
        name: cakephp
    - name: Deploy Image Uploader with persistent storage
      include_role:
        name: imageuploader
    - name: Deploy Todo application, including mongodb, postgresql, gogs, all with persistent storage
      include_role:
        name: todoapp
    - name: Deploy rocket chat with mongodb stateful set and persistent storage
      include_role:
        name: rocket
...
