---
- name: Populate OpenShift with projects
  hosts: 127.0.0.1
  connection: local
  vars:
    cakephp_state: "present"
    imageuploader_state: "present"
    rocket_state: "present"
    todo_state: "present"
    articles_state: "present"
    remove_all_apps: false
    api_entrypoint: "https://api.cluster-ocs-1692.ocs-1692.example.opentlc.com:6443"
    api_ca_cert: "ingress-ca.crt"
  module_defaults:
    group/k8s:
      host: "{{ api_entrypoint }}"
      ca_cert: "{{ api_ca_cert }}"
  tasks:
    - name: Define if all applications are being unisntalled
      set_fact:
        cakephp_state: "absent"
        imageuploader_state: "absent"
        rocket_state: "absent"
        todo_state: "absent"
        articles_state: "absent"
      when: remove_all_apps
    - name: Load user credentials for OCP
      include_vars: 
        file: secret
    - name: Log in to obtain access token
      k8s_auth:
        username: "{{ ocp_user }}"
        password: "{{ ocp_pass }}"
      register: _auth_result
    - name: detect OCP version 3 or 4
      uri:
        url: "{{ api_entrypoint }}/version"
        validate_certs: no
        method: GET
        headers:
          Authorization: Bearer {{ _auth_result.k8s_auth.api_key }}
          Accept: application/json, */*
      register: _version
    - name: Define var current_ocp_version
      set_fact:
        current_ocp_version: "{{ _version.json.minor|regex_replace('(..).*$','\\1') }}"
    #Next needs to be a separate task because it depends on the preivous variable current_ocp_version
    - name: Define API entry point for project request according to OCP version
      set_fact:
        project_api_version: "{% if current_ocp_version|int <= 11 %}v1{% else %}project.openshift.io/v1{% endif %}"
    - name: Deploy Cakephp with NO persistent storage
      include_role:
        name: cakephp
    - name: Deploy Image Uploader with persistent storage
      include_role:
        name: imageuploader
    - name: Deploy Todo application, including mongodb, postgresql, gogs, all with persistent storage
      include_role:
        name: todoapp
      # Minor version 11 is the highest in OCP 3 branch, for 3.11
      when: current_ocp_version|int <= 11 or todo_state == "absent"
    - name: Deploy rocket chat with mongodb stateful set and persistent storage
      include_role:
        name: rocket
    - name: Deploy articles app
      include_role:
        name: articles
    - name: Log out to revoke access token
      k8s_auth:
        state: absent
        api_key: "{{ _auth_result.k8s_auth.api_key }}"
      when: _auth_result.k8s_auth.api_key is defined
...
