apiVersion: v1
kind: Secret
metadata:
  name: tale-liv-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5ZWNvc3lzdGVtLXF1YXktcXVheS1lbnRlcnByaXNlLmFwcHMuc3liaWwudGFsZS5yaGNlZS5zdXBwb3J0IjogewogICAgICAiYXV0aCI6ICJkR0ZzWlN0c2FYWTZRa1pLV0ROR01UbEpOazlYV0RKVVN6QkVSREpZU0U1RU1GWkxRMWhaU3poTVF6UlZSamhXVlRFNFJEVk9OVTFOTjFoWVNscFNOVVJZU2tKQ05rdFpTUT09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
