---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy the application server
    template.alpha.openshift.io/wait-for-ready: "true"
  name: "{{ cakephp_app_name }}"
spec:
  replicas: 1
  selector:
    name: "{{ cakephp_app_name }}"
  strategy:
    recreateParams:
      pre:
        execNewPod:
          command:
          - ./migrate-database.sh
          containerName: cakephp-mysql-example
        failurePolicy: Retry
    type: Recreate
  template:
    metadata:
      labels:
        name: "{{ cakephp_app_name }}"
      name: "{{ cakephp_app_name }}"
    spec:
      containers:
      - env:
        - name: DATABASE_SERVICE_NAME
          value: "{{ database_service_name }}"
        - name: DATABASE_ENGINE
          value: "{{ database_engine }}"
        - name: DATABASE_NAME
          value: "{{ database_name }}"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: "{{ secret_name }}"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: "{{ secret_name }}"
        - name: CAKEPHP_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              key: cakephp-secret-token
              name: "{{ secret_name }}"
        - name: CAKEPHP_SECURITY_SALT
          valueFrom:
            secretKeyRef:
              key: cakephp-security-salt
              name: "{{ secret_name }}"
        - name: OPCACHE_REVALIDATE_FREQ
          value: "{{opcache_revalidate_freq }}"
        image: ' '
        livenessProbe:
          httpGet:
            path: /health.php
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 3
        name: "{{ cakephp_app_name }}"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health.php
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 60
          timeoutSeconds: 3
        resources:
          limits:
            memory: 512Mi
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - "{{ cakephp_app_name }}"
      from:
        kind: ImageStreamTag
        name: "{{ cakephp_app_name }}:latest"
    type: ImageChange
  - type: ConfigChange
...
