---
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
  name: "{{ cakephp_app_name }}"
spec:
  output:
    pushSecret:
      name: tale-liv-pull-secret
    to:
      kind: DockerImage
      name: quayecosystem-quay-quay-enterprise.apps.sybil.tale.rhcee.support/tale/cakephp:latest
  postCommit:
    script: ./vendor/bin/phpunit
  source:
    git:
      uri: "{{ source_repository_url }}"
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: "php:{{ php_version }}"
        namespace: openshift
    type: Source
  triggers:
  - type: ConfigChange
  - github:
      secret: "{{ github_webhook_secret }}"
    type: GitHub
...
