---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ imageuploader_app_name }}"
  name: "{{ imageuploader_app_name }}"
spec:
  replicas: 1
  selector:
    app: "{{ imageuploader_app_name }}"
    deploymentconfig: "{{ imageuploader_app_name }}"
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: "{{ imageuploader_app_name }}"
        deploymentconfig: "{{ imageuploader_app_name }}"
    spec:
      containers:
      - image: ' '
        imagePullPolicy: Always
        name: "{{ imageuploader_app_name }}"
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: 
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /opt/app-root/src/uploads
          name: volume-z644l
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: volume-z644l
        persistentVolumeClaim:
          claimName: "{{ imageuploader_app_name }}"
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - "{{ imageuploader_app_name }}"
      from:
        kind: ImageStreamTag
        name: "{{ imageuploader_app_name }}:latest"
        namespace: "{{ namespace }}"
    type: ImageChange
...
