---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ database_service_name }}"
spec:
  accessModes:
  - ReadWriteOnce
{% if storage_class != "" %}
  storageClassName: "{{ storage_class }}"
{% endif %}
  resources:
    requests:
      storage: "{{ volume_capacity }}"
...
