---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ database_service_name }}"
spec:
  accessModes:
  - ReadWriteOnce
{% if articles_storage_class != "" %}
  storageClassName: "{{ articles_storage_class }}"
{% endif %}
  resources:
    requests:
      storage: "{{ volume_capacity }}"
...
