---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy the application server
  name: {{ name }}
spec:
  replicas: 1
  selector:
    name: {{ name }}
  strategy:
    recreateParams:
      pre:
        execNewPod:
          command:
          - ./migrate-database.sh
          containerName: {{ name }}
        failurePolicy: Abort
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ name }}
      name: {{ name }}
    spec:
      containers:
      - env:
        - name: DATABASE_SERVICE_NAME
          value: "{{ database_service_name }}"
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ name }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ name }}
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: keybase
              name: {{ name }}
        - name: POSTGRESQL_DATABASE
          value: "{{ database_name }}"
        - name: POSTGRESQL_MAX_CONNECTIONS
          value: "{{ postgresql_max_connections }}"
        - name: POSTGRESQL_SHARED_BUFFERS
          value: "{{ postgresql_shared_buffers }}"
        - name: APPLICATION_USER
          valueFrom:
            secretKeyRef:
              key: application-user
              name: {{ name }}
        - name: APPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              key: application-password
              name: {{ name }}
        - name: RAILS_ENV
          value: "{{ rails_env }}"
        image: ' '
        livenessProbe:
          httpGet:
            path: /articles
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 3
        name: {{ name }}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /articles
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            memory: "{{ memory_limit }}"
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ name }}
      from:
        kind: ImageStreamTag
        name: {{ name }}:latest
    type: ImageChange
  - type: ConfigChange
...
