---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
  labels:
    app: "{{ rocket_app_name }}"
  name:  "{{ rocket_app_name }}"
spec:
  replicas: 1
  selector:
    app: "{{ rocket_app_name }}"
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: "{{ rocket_app_name }}"
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: mongodb://mongodb_user:mongodb_password@mongodb:27017/mongodb?replicaSet=rs0
        image: ' '
        name:  "{{ rocket_app_name }}"
        ports:
          - containerPort: 3000
            protocol: TCP
        volumeMounts:
        - mountPath: /app/uploads
          name: rocketchat-volume-1
      volumes:
      - emptyDir: {}
        name: rocketchat-volume-1
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - "{{ rocket_app_name }}"
      from:
        kind: ImageStreamTag
        name: "{{ rocket_app_name }}:0.63.3"
        namespace: "{{ rocket_namespace }}"
    type: ImageChange
  - type: ConfigChange
...
