---
# defaults file for todoapp
namespace: todoapp
todo_app_name: todo-app
mongodb_application_name: mongodb
mongodb_user_definition: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
mongodb_password_definition: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
mongodb_admin_password_definition: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
github_trigger_secret_definition: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
generic_trigger_secret_definition: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
mongodb_database: tododb
memory_limit: "128Mi"
mongo_memory_limit: "128Mi"
context_dir: openshift-cicd-flask-mongo
git_ref: master
git_uri: https://github.com/OpenShiftInAction/chapter6
gogs_version: "0.11.29"
gogs_postgresql_password_definition: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
gogs_password_definition: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters') }}"
...
