---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: gogs
  name: gogs
spec:
  replicas: 1
  selector:
    app: gogs
    deploymentconfig: gogs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gogs
        deploymentconfig: gogs
    spec:
      containers:
      - image: ' '
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: gogs
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /opt/gogs/data
          name: gogs-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gogs-data
        persistentVolumeClaim:
          claimName: gogs
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gogs
      from:
        kind: ImageStreamTag
        name: "gogs:{{ gogs_version }}"
    type: ImageChange
...
