---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-gogs
spec:
  accessModes:
    - ReadWriteOnce
{% if postgre_gogs_storage_class != "" %}
  storageClassName: "{{ postgre_gogs_storage_class }}"
{% endif %}
  resources:
    requests:
      storage: 2Gi 
...
