---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    component: "{{ todo_app_name }}"
  name: "{{ todo_app_name }}"
spec:
  replicas: 1
  selector:
    component: "{{ todo_app_name }}"
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        component: "{{ todo_app_name }}"
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DB_HOST
          value: "{{ mongodb_application_name }}"
        - name: MONGO_CONNECTION_URI
          value: "mongodb://{{ mongodb_user }}:{{ mongodb_password }}@{{ mongodb_application_name }}/{{ mongodb_database }}"
        image: "{{ todo_app_name }}"
        imagePullPolicy: IfNotPresent
        name: "{{ todo_app_name }}"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: "{{ memory_limit }}"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - "{{ todo_app_name }}"
      from:
        kind: ImageStreamTag
        name: "{{ todo_app_name }}:latest"
    type: ImageChange
...
